apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: project1-webapp-secrets
  namespace: project1
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: project1-webapp-secrets
    creationPolicy: Owner
  data:
    - secretKey: dbPassword
      remoteRef:
        key: REPLACE_WITH_DB_SECRET_ARN
        property: password
