apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: project1-webapp
  namespace: project1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project1-webapp
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
